import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  page: {
    flex: 1,
    width: '100%',
    backgroundColor: '#F7F9FC',
    paddingTop: 28,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 20,
    paddingBottom: 118,
  },
  headerCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 22,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  greeting: {
    fontSize: 16,
    color: '#64748B',
    marginBottom: 6,
  },
  greetingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 10,
  },
  name: {
    fontSize: 32,
    fontWeight: '700',
    color: '#0F172A',
  },
  headerIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#EFF6FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  location: {
    fontSize: 14,
    color: '#475569',
    lineHeight: 20,
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 14,
    marginBottom: 24,
  },
  actionCard: {
    width: '48%',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    paddingVertical: 18,
    paddingHorizontal: 16,
    justifyContent: 'center',
    minHeight: 120,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  actionIcon: {
    width: 42,
    height: 42,
    borderRadius: 8,
    backgroundColor: '#EFF6FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0F172A',
    marginTop: 10,
  },
  actionSubtitle: {
    fontSize: 12,
    color: '#64748B',
    marginTop: 4,
    lineHeight: 18,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  sectionLinkButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0F172A',
  },
  sectionLink: {
    fontSize: 14,
    color: '#2563EB',
    fontWeight: '700',
  },
  appointmentCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 16,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  appointmentHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
    gap: 14,
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 8,
    backgroundColor: '#E0F2FE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0C4A6E',
  },
  appointmentInfo: {
    flex: 1,
    paddingTop: 1,
  },
  appointmentDoctor: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0F172A',
    marginBottom: 3,
  },
  appointmentSpecialty: {
    fontSize: 13,
    color: '#64748B',
  },
  appointmentMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginLeft: 66,
  },
  dateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  tag: {
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  tagText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#D97706',
  },
  dateText: {
    fontSize: 12,
    color: '#475569',
  },
  appointmentLoadingRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 76,
    paddingTop: 8,
    paddingBottom: 10,
    paddingHorizontal: 10,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    shadowColor: '#0F172A',
    shadowOpacity: 0.08,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: -4 },
    elevation: 18,
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 56,
    borderRadius: 8,
    gap: 3,
  },
  tabItemActive: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 56,
    borderRadius: 8,
    backgroundColor: '#EFF6FF',
    gap: 3,
  },
  tabLabel: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '600',
  },
  tabLabelActive: {
    color: '#2563EB',
    fontSize: 11,
    fontWeight: '700',
  },
  perfilScreen: {
    flex: 1,
  },
  perfilScrollView: {
    flex: 1,
    backgroundColor: '#F7F9FC',
  },
  perfilContent: {
    paddingHorizontal: 18,
    paddingBottom: 118,
  },
  perfilTopBar: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  perfilBrandAvatar: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: '#139CA3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  perfilBrandText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  perfilMenuButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  perfilProfileHeader: {
    alignItems: 'center',
    marginBottom: 26,
  },
  perfilProfileIcon: {
    width: 74,
    height: 74,
    borderRadius: 12,
    backgroundColor: '#E0F2F1',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  perfilName: {
    color: '#111827',
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 6,
    textAlign: 'center',
  },
  perfilEmailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 8,
  },
  perfilEmail: {
    color: '#6B7280',
    fontSize: 14,
  },
  perfilRoleBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#DFF4F3',
    borderWidth: 1,
    borderColor: '#B9E5E2',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  perfilRoleText: {
    color: '#147A80',
    fontSize: 12,
    fontWeight: '700',
  },
  perfilStatsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 28,
  },
  perfilTotalsInfoBox: {
    minHeight: 42,
    borderRadius: 8,
    backgroundColor: '#F1FBFA',
    borderWidth: 1,
    borderColor: '#B9E5E2',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginTop: -14,
    marginBottom: 18,
  },
  perfilTotalsInfoText: {
    flex: 1,
    color: '#147A80',
    fontSize: 12,
    fontWeight: '700',
  },
  perfilStatCard: {
    flex: 1,
    minHeight: 78,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#EEF2F7',
    shadowColor: '#0F172A',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  perfilStatNumber: {
    color: '#111827',
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 4,
  },
  perfilStatSuccess: {
    color: '#13A085',
  },
  perfilStatDanger: {
    color: '#DC3444',
  },
  perfilStatLabel: {
    color: '#6B7280',
    fontSize: 12,
  },
  perfilInfoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    paddingHorizontal: 18,
    paddingVertical: 20,
    borderWidth: 1,
    borderColor: '#EEF2F7',
    marginBottom: 20,
    shadowColor: '#0F172A',
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  perfilSectionTitle: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
  },
  perfilSectionHeader: {
    minHeight: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  perfilErrorBox: {
    minHeight: 42,
    borderRadius: 8,
    backgroundColor: '#FFF5F6',
    borderWidth: 1,
    borderColor: '#F0CBD0',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginBottom: 16,
  },
  perfilErrorText: {
    flex: 1,
    color: '#9F2531',
    fontSize: 12,
    fontWeight: '700',
  },
  perfilInfoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
  },
  perfilInfoIcon: {
    width: 38,
    height: 38,
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  perfilInfoTextGroup: {
    flex: 1,
  },
  perfilInfoLabel: {
    color: '#6B7280',
    fontSize: 12,
    marginBottom: 3,
  },
  perfilInfoValue: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '700',
  },
  perfilLogoutButton: {
    minHeight: 46,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#F0CBD0',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  perfilLogoutText: {
    color: '#C2414B',
    fontSize: 14,
    fontWeight: '800',
  },
  perfilDrawerRoot: {
    flex: 1,
    flexDirection: 'row',
  },
  perfilDrawerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.38)',
  },
  perfilDrawerPanel: {
    width: '82%',
    maxWidth: 320,
    height: '100%',
    backgroundColor: '#FFFFFF',
    paddingTop: 22,
    paddingHorizontal: 18,
    paddingBottom: 28,
    shadowColor: '#0F172A',
    shadowOpacity: 0.18,
    shadowRadius: 24,
    shadowOffset: { width: 8, height: 0 },
    elevation: 24,
  },
  perfilDrawerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    marginBottom: 14,
  },
  perfilDrawerAvatar: {
    width: 42,
    height: 42,
    borderRadius: 8,
    backgroundColor: '#139CA3',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  perfilDrawerAvatarText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  perfilDrawerIdentity: {
    flex: 1,
  },
  perfilDrawerName: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 3,
  },
  perfilDrawerEmail: {
    color: '#6B7280',
    fontSize: 12,
  },
  perfilDrawerCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  perfilDrawerMenu: {
    gap: 8,
    marginBottom: 20,
  },
  perfilDrawerItem: {
    minHeight: 50,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    backgroundColor: '#F8FAFC',
  },
  perfilDrawerItemIcon: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: '#E0F2F1',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  perfilDrawerItemText: {
    flex: 1,
    color: '#111827',
    fontSize: 14,
    fontWeight: '700',
  },
  perfilDrawerLogoutButton: {
    marginTop: 'auto',
    minHeight: 46,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#F0CBD0',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  perfilDrawerLogoutText: {
    color: '#C2414B',
    fontSize: 14,
    fontWeight: '800',
  },
});
