import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  topBar: {
    minHeight: 68,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
  },
  logo: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#159CA3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  menuButton: {
    width: 42,
    height: 42,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollView: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 26,
    paddingBottom: 118,
  },
  stepMeta: {
    minHeight: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  backText: {
    color: '#6B7280',
    fontSize: 14,
  },
  stepText: {
    color: '#4B5563',
    fontSize: 14,
  },
  progressTrack: {
    height: 6,
    borderRadius: 999,
    backgroundColor: '#E8EDF2',
    marginBottom: 26,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#1E9EAA',
  },
  title: {
    color: '#111827',
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 8,
  },
  subtitle: {
    color: '#6B7280',
    fontSize: 16,
    lineHeight: 22,
    marginBottom: 22,
  },
  specialtyGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 14,
    marginBottom: 22,
  },
  specialtyCard: {
    width: '47.8%',
    minHeight: 116,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#EEF2F7',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingVertical: 16,
    shadowColor: '#0F172A',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  selectedCard: {
    borderColor: '#159CA3',
    borderWidth: 2,
    backgroundColor: '#F1FBFA',
  },
  specialtyIcon: {
    width: 48,
    height: 48,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  specialtyName: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  feedbackCard: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 18,
    marginBottom: 16,
  },
  feedbackTitle: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '800',
    marginTop: 8,
    marginBottom: 6,
    textAlign: 'center',
  },
  feedbackText: {
    color: '#6B7280',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 8,
    textAlign: 'center',
  },
  retryButton: {
    minHeight: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#BFE4E5',
    backgroundColor: '#F1FBFA',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 14,
    marginTop: 12,
  },
  retryButtonText: {
    color: '#159CA3',
    fontSize: 13,
    fontWeight: '800',
  },
  primaryButton: {
    minHeight: 52,
    borderRadius: 8,
    backgroundColor: '#1E9EAA',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#159CA3',
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
    marginTop: 8,
  },
  primaryButtonDisabled: {
    backgroundColor: '#86CBD2',
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  doctorCard: {
    minHeight: 118,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#EEF2F7',
    backgroundColor: '#FFFFFF',
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 26,
    shadowColor: '#0F172A',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  selectedDoctorCard: {
    borderColor: '#159CA3',
    borderWidth: 2,
    backgroundColor: '#ECFAFA',
  },
  avatar: {
    width: 58,
    height: 58,
    borderRadius: 8,
    backgroundColor: '#E3F7F6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  doctorInfo: {
    flex: 1,
  },
  doctorNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 3,
  },
  doctorName: {
    flex: 1,
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
  },
  doctorLicense: {
    color: '#4B5563',
    fontSize: 13,
    marginBottom: 4,
  },
  doctorDescription: {
    color: '#6B7280',
    fontSize: 13,
    marginBottom: 8,
  },
  dayTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  dayTag: {
    borderRadius: 999,
    backgroundColor: '#EEF2F7',
    paddingHorizontal: 9,
    paddingVertical: 3,
  },
  dayTagText: {
    color: '#6B7280',
    fontSize: 11,
    fontWeight: '700',
  },
  calendarCard: {
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EEF2F7',
    paddingHorizontal: 28,
    paddingVertical: 24,
    marginBottom: 24,
    shadowColor: '#0F172A',
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  monthRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  monthButton: {
    width: 32,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#EEF2F7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  monthTitle: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '700',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  weekDay: {
    width: `${100 / 7}%`,
    textAlign: 'center',
    color: '#6B7280',
    fontSize: 13,
    marginBottom: 10,
  },
  calendarDay: {
    width: `${100 / 7}%`,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  calendarDaySelected: {
    backgroundColor: '#CFF3EE',
    borderRadius: 999,
  },
  calendarDayDisabled: {
    opacity: 0.45,
  },
  calendarDayText: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '600',
  },
  calendarDayMuted: {
    color: '#C6CDD5',
  },
  calendarDaySelectedText: {
    color: '#159CA3',
    fontWeight: '800',
  },
  calendarDayDisabledText: {
    color: '#D1D5DB',
  },
  hoursTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 12,
  },
  hoursTitle: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '700',
  },
  hoursGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 9,
    marginBottom: 20,
  },
  hourButton: {
    width: '22.8%',
    minHeight: 42,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EEF2F7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  hourButtonSelected: {
    backgroundColor: '#159CA3',
    borderColor: '#159CA3',
  },
  hourText: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '700',
  },
  hourTextSelected: {
    color: '#FFFFFF',
  },
  summaryCard: {
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EEF2F7',
    padding: 18,
    marginBottom: 20,
    shadowColor: '#0F172A',
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  summaryItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  summaryIcon: {
    width: 44,
    height: 44,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  summaryIconTeal: {
    backgroundColor: '#E3F7F6',
  },
  summaryIconYellow: {
    backgroundColor: '#FFF8D7',
  },
  summaryIconBlue: {
    backgroundColor: '#E9F4FB',
  },
  summaryLabel: {
    color: '#6B7280',
    fontSize: 12,
    marginBottom: 4,
  },
  summaryValue: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '800',
  },
  observationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 10,
  },
  observationTitle: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '700',
  },
  textArea: {
    minHeight: 92,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#1E9EAA',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    paddingVertical: 12,
    color: '#111827',
    fontSize: 16,
    lineHeight: 22,
    marginBottom: 14,
  },
  inlineError: {
    minHeight: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#F0CBD0',
    backgroundColor: '#FFF5F6',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginBottom: 12,
  },
  inlineErrorText: {
    flex: 1,
    color: '#9F2531',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  successIconWrap: {
    width: 84,
    height: 84,
    borderRadius: 999,
    backgroundColor: '#E0F6F1',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 22,
  },
  successTitle: {
    color: '#111827',
    fontSize: 24,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 8,
  },
  successSubtitle: {
    color: '#6B7280',
    fontSize: 15,
    textAlign: 'center',
    marginBottom: 28,
  },
  successCard: {
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EEF2F7',
    padding: 18,
    marginBottom: 22,
    shadowColor: '#0F172A',
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  successRow: {
    marginBottom: 12,
  },
  successDateRow: {
    flexDirection: 'row',
    marginTop: 4,
    marginBottom: 14,
  },
  successDateColumn: {
    flex: 1,
  },
  inlineInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  divider: {
    height: 1,
    backgroundColor: '#EEF2F7',
    marginBottom: 14,
  },
  codeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 10,
  },
  codeBox: {
    minHeight: 72,
    borderRadius: 8,
    backgroundColor: '#E9EEF3',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  confirmationCode: {
    color: '#159CA3',
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 3,
    marginBottom: 8,
  },
  codeHint: {
    color: '#6B7280',
    fontSize: 11,
  },
  secondaryButton: {
    minHeight: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  secondaryButtonText: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '800',
  },
  listHeader: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  listTitle: {
    color: '#111827',
    fontSize: 20,
    fontWeight: '800',
  },
  refreshButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D6EDEE',
    backgroundColor: '#F1FBFA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterBlock: {
    marginBottom: 14,
  },
  filterLabel: {
    color: '#4B5563',
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 7,
  },
  filterButton: {
    minHeight: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D6EDEE',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 13,
  },
  filterButtonText: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '800',
  },
  filterDropdown: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D6EDEE',
    backgroundColor: '#FFFFFF',
    marginTop: 8,
    overflow: 'hidden',
  },
  filterOption: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 13,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF2F7',
  },
  filterOptionSelected: {
    backgroundColor: '#F1FBFA',
  },
  filterOptionText: {
    color: '#4B5563',
    fontSize: 14,
    fontWeight: '700',
  },
  filterOptionTextSelected: {
    color: '#159CA3',
    fontWeight: '900',
  },
  inlineSuccess: {
    minHeight: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#BFE4E5',
    backgroundColor: '#F1FBFA',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginBottom: 14,
  },
  inlineSuccessText: {
    flex: 1,
    color: '#147A80',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  consultationCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#EEF2F7',
    padding: 18,
    marginBottom: 14,
    shadowColor: '#0F172A',
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  consultationCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  consultationAvatar: {
    width: 54,
    height: 54,
    borderRadius: 8,
    backgroundColor: '#E3F7F6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  consultationHeaderInfo: {
    flex: 1,
  },
  consultationDoctorName: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 3,
  },
  consultationSpecialty: {
    color: '#6B7280',
    fontSize: 13,
  },
  statusBadge: {
    borderRadius: 999,
    backgroundColor: '#FFF8D7',
    borderWidth: 1,
    borderColor: '#F4E7A3',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  statusBadgeWarning: {
    backgroundColor: '#FFF8D7',
    borderColor: '#F4E7A3',
  },
  statusBadgeSuccess: {
    backgroundColor: '#DCFCE7',
    borderColor: '#BBF7D0',
  },
  statusBadgeDanger: {
    backgroundColor: '#FDE7EC',
    borderColor: '#F5C5CF',
  },
  statusBadgeNeutral: {
    backgroundColor: '#EEF2F7',
    borderColor: '#E5E7EB',
  },
  statusText: {
    color: '#C89A12',
    fontSize: 11,
    fontWeight: '800',
  },
  statusTextWarning: {
    color: '#C89A12',
  },
  statusTextSuccess: {
    color: '#15803D',
  },
  statusTextDanger: {
    color: '#C2414B',
  },
  statusTextNeutral: {
    color: '#64748B',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginBottom: 14,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  metaText: {
    color: '#6B7280',
    fontSize: 14,
    fontWeight: '600',
  },
  consultationCodeBox: {
    minHeight: 70,
    borderRadius: 8,
    backgroundColor: '#F1F4F7',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
    marginBottom: 14,
  },
  consultationCodeLabel: {
    color: '#6B7280',
    fontSize: 11,
    marginBottom: 5,
  },
  consultationCodeText: {
    color: '#159CA3',
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 2,
  },
  consultationObservation: {
    color: '#6B7280',
    fontSize: 13,
    fontStyle: 'italic',
    marginBottom: 18,
  },
  consultationActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  consultationEditButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 34,
  },
  consultationEditText: {
    color: '#159CA3',
    fontSize: 14,
    fontWeight: '800',
  },
  consultationCancelButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 34,
  },
  consultationCancelText: {
    color: '#D1435B',
    fontSize: 14,
    fontWeight: '700',
  },
});
