import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  page: {
    flex: 1,
    width: '100%',
    backgroundColor: '#F7F9FC',
    paddingTop: 34,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 18,
    paddingBottom: 136,
  },
  topBar: {
    minHeight: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  brandAvatar: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: '#139CA3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    color: '#0F172A',
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 26,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 12,
    marginBottom: 20,
  },
  statCard: {
    width: '48%',
    minHeight: 96,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EEF2F7',
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: '#0F172A',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 5,
  },
  statIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  statValue: {
    color: '#111827',
    fontSize: 23,
    fontWeight: '800',
    lineHeight: 27,
  },
  statLabel: {
    color: '#64748B',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 2,
  },
  segmentedControl: {
    minHeight: 42,
    backgroundColor: '#E8EDF2',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 5,
    marginBottom: 20,
  },
  segmentButton: {
    flex: 1,
    minHeight: 32,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  segmentButtonActive: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#0F172A',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  segmentText: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '700',
  },
  segmentTextActive: {
    color: '#111827',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  sectionTitle: {
    color: '#0F172A',
    fontSize: 18,
    fontWeight: '800',
  },
  addButton: {
    minHeight: 42,
    borderRadius: 12,
    backgroundColor: '#139CA3',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingHorizontal: 14,
  },
  addButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
  },
  doctorCard: {
    minHeight: 84,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#EEF2F7',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 14,
    shadowColor: '#0F172A',
    shadowOpacity: 0.07,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 5,
  },
  doctorIcon: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: '#EAF7F7',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  doctorInfo: {
    flex: 1,
    minWidth: 0,
  },
  doctorName: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '800',
  },
  doctorMeta: {
    color: '#64748B',
    fontSize: 12,
    marginTop: 3,
  },
  dayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 8,
  },
  dayBadge: {
    borderRadius: 6,
    backgroundColor: '#EEF2F7',
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  dayText: {
    color: '#64748B',
    fontSize: 10,
    fontWeight: '800',
  },
  doctorActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginLeft: 8,
  },
  actionButton: {
    width: 28,
    height: 28,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteActionButton: {
    width: 28,
    height: 28,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFF5F6',
  },
  deleteActionButtonDisabled: {
    width: 28,
    height: 28,
    borderRadius: 7,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F1F5F9',
    opacity: 0.45,
  },
  userList: {
    gap: 8,
  },
  userCard: {
    minHeight: 68,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#EEF2F7',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 9,
    shadowColor: '#0F172A',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  userAvatar: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: '#EAF7F7',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  userInfo: {
    flex: 1,
    minWidth: 0,
  },
  userName: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '800',
  },
  userEmail: {
    color: '#64748B',
    fontSize: 11,
    marginTop: 2,
  },
  userMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 6,
  },
  userRoleBadge: {
    borderRadius: 5,
    backgroundColor: '#EEF2F7',
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  userRoleText: {
    color: '#475569',
    fontSize: 9,
    fontWeight: '800',
  },
  userStatus: {
    color: '#139CA3',
    fontSize: 10,
    fontWeight: '800',
  },
  userStatusInactive: {
    color: '#C2414B',
    fontSize: 10,
    fontWeight: '800',
  },
  userActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginLeft: 8,
  },
  emptyCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EEF2F7',
    alignItems: 'center',
    padding: 24,
    shadowColor: '#0F172A',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  emptyTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '800',
    marginTop: 10,
  },
  emptyText: {
    color: '#64748B',
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 19,
    marginTop: 5,
  },
  bottomBar: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 12,
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 18,
    paddingVertical: 8,
    paddingHorizontal: 8,
    shadowColor: '#0F172A',
    shadowOpacity: 0.14,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 18,
  },
  tabItem: {
    flex: 1,
    minHeight: 60,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  tabItemActive: {
    flex: 1,
    minHeight: 60,
    borderRadius: 12,
    backgroundColor: '#F0FAFA',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  tabIconBox: {
    width: 30,
    height: 27,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabIconBoxActive: {
    width: 30,
    height: 27,
    borderRadius: 9,
    backgroundColor: '#139CA3',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabLabel: {
    color: '#64748B',
    fontSize: 9,
    fontWeight: '700',
  },
  tabLabelActive: {
    color: '#139CA3',
    fontSize: 9,
    fontWeight: '800',
  },
  drawerRoot: {
    flex: 1,
    flexDirection: 'row',
  },
  drawerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.38)',
  },
  drawerPanel: {
    width: '82%',
    maxWidth: 320,
    height: '100%',
    backgroundColor: '#FFFFFF',
    paddingTop: 34,
    paddingHorizontal: 18,
    paddingBottom: 28,
    shadowColor: '#0F172A',
    shadowOpacity: 0.18,
    shadowRadius: 24,
    shadowOffset: { width: 8, height: 0 },
    elevation: 24,
  },
  drawerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    marginBottom: 14,
  },
  drawerAvatar: {
    width: 42,
    height: 42,
    borderRadius: 10,
    backgroundColor: '#139CA3',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  drawerAvatarText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  drawerIdentity: {
    flex: 1,
  },
  drawerTitle: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 3,
  },
  drawerSubtitle: {
    color: '#64748B',
    fontSize: 12,
  },
  drawerCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  drawerMenu: {
    gap: 8,
    marginBottom: 20,
  },
  drawerItem: {
    minHeight: 50,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    backgroundColor: '#F8FAFC',
  },
  drawerItemActive: {
    minHeight: 50,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    backgroundColor: '#EAF7F7',
    borderWidth: 1,
    borderColor: '#C9ECEA',
  },
  drawerItemIcon: {
    width: 34,
    height: 34,
    borderRadius: 9,
    backgroundColor: '#E0F2F1',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  drawerItemIconActive: {
    width: 34,
    height: 34,
    borderRadius: 9,
    backgroundColor: '#139CA3',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  drawerItemText: {
    flex: 1,
    color: '#111827',
    fontSize: 14,
    fontWeight: '700',
  },
  drawerItemTextActive: {
    flex: 1,
    color: '#147A80',
    fontSize: 14,
    fontWeight: '800',
  },
  drawerLogoutButton: {
    marginTop: 'auto',
    minHeight: 46,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#F0CBD0',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  drawerLogoutText: {
    color: '#C2414B',
    fontSize: 14,
    fontWeight: '800',
  },
  funcaoSelectButton: {
    width: '100%',
    minHeight: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#F8FAFC',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  funcaoSelectText: {
    color: '#0F172A',
    fontSize: 16,
    fontWeight: '700',
  },
  funcaoModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.46)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  funcaoModalCard: {
    width: '100%',
    maxWidth: 390,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 14,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 12,
  },
  funcaoModalTitle: {
    color: '#0F172A',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 12,
    textAlign: 'center',
  },
  funcaoOption: {
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 13,
    marginBottom: 8,
  },
  funcaoOptionActive: {
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#A8DBD8',
    backgroundColor: '#F0FAFA',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 13,
    marginBottom: 8,
  },
  funcaoOptionText: {
    color: '#475569',
    fontSize: 14,
    fontWeight: '700',
  },
  funcaoOptionTextActive: {
    color: '#147A80',
    fontSize: 14,
    fontWeight: '800',
  },
  funcaoCancelButton: {
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
  },
  funcaoCancelText: {
    color: '#475569',
    fontSize: 14,
    fontWeight: '800',
  },
  updateModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.46)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  updateModalCard: {
    width: '100%',
    maxWidth: 390,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 12,
  },
  updateModalHeader: {
    minHeight: 36,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  updateModalTitle: {
    color: '#0F172A',
    fontSize: 18,
    fontWeight: '800',
  },
  updateCloseButton: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  updateField: {
    marginBottom: 10,
  },
  updateLabel: {
    color: '#334155',
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 6,
  },
  updateInput: {
    width: '100%',
    minHeight: 46,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#DDE5EE',
    backgroundColor: '#F8FAFC',
    color: '#0F172A',
    fontSize: 14,
    fontWeight: '600',
    paddingHorizontal: 12,
  },
  updateSelectButton: {
    width: '100%',
    minHeight: 46,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#DDE5EE',
    backgroundColor: '#F8FAFC',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
  },
  updateSelectText: {
    color: '#0F172A',
    fontSize: 14,
    fontWeight: '700',
  },
  statusOptions: {
    flexDirection: 'row',
    gap: 8,
  },
  statusOption: {
    flex: 1,
    minHeight: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#DDE5EE',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusOptionActive: {
    flex: 1,
    minHeight: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#A8DBD8',
    backgroundColor: '#F0FAFA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusOptionText: {
    color: '#64748B',
    fontSize: 13,
    fontWeight: '800',
  },
  statusOptionTextActive: {
    color: '#147A80',
    fontSize: 13,
    fontWeight: '800',
  },
  updateActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
  },
  updateCancelButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  updateCancelText: {
    color: '#475569',
    fontSize: 14,
    fontWeight: '800',
  },
  updateSaveButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#139CA3',
  },
  updateSaveText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
});
